### ISSUE TITLE
Pricing has inertia?

### ISSUE THREAD

**Issue by selsrog** [quintinnicolas/elia-py#13]
Hi

not really an issue, than well a question: I would like to have the current quarter price. When using the script to pull all of today's data, it lags like 10 hours. Is this normal?

Thanks!

**Comment by quintinnicolas** [comment]
Hello @selsrog ,

Thanks for posting this question. When querying data for the last hours, it is indeed possible that the data is not yet available through the API. You can always validate your queries via the [Open Data platform of ELIA](https://opendata.elia.be/explore/dataset/ods047/table/?sort=datetime) where you should have exactly the same results as with the elia-py client.
