### ISSUE TITLE
Update to BASE_URL necessary

### ISSUE THREAD

**Issue by thomasdemoor** [quintinnicolas/elia-py#16]
Elia advertises the use of https://opendata.elia.be/api/explore/v2.0/ as base url (https://opendata.elia.be/api/explore/v2.0/console). 

Was not a problem so far, but recently datasets are showing differences: 

https://opendata.elia.be/api/explore/v2.0/catalog/datasets/ods086/exports/json

vs.

https://opendata.elia.be/api/v2/catalog/datasets/ods086/exports/json (no data after 20/10/2024)

**Comment by quintinnicolas** [comment]
Thanks @thomasdemoor for filing this issue! 
It has been addresses in PR https://github.com/quintinnicolas/elia-py/pull/18, now available in elia-py [0.3.1](https://github.com/quintinnicolas/elia-py/releases/tag/v0.3.1).
