### ISSUE TITLE
TypeError: _generate_range() got an unexpected keyword argument 'closed'

### ISSUE THREAD

**Issue by RobbeNK** [quintinnicolas/elia-py#8]
pd.date_range function still uses the closed keyword as the one with keyword inclusive is commented out. Is it possible to install a version where it uses the inclusive keyword? Thanks in advance

**Comment by quintinnicolas** [comment]
Hello @RobbeNK thanks for filing this issue. 
It should be fixed in release [v.0.2.2](https://github.com/quintinnicolas/elia-py/releases/tag/v0.2.2). Feel free to check it out.
